server:
  port: 8081
spring:
  application:
    name: gestion-produits
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/gestion-produits
    password:
  jpa:
    hibernate:
      ddl-auto: update