server:
  port: 8082
spring:
  application:
    name: gestion-commandes
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/gestion-commandes
    password:
  jpa:
    hibernate:
      ddl-auto: update