server:
  port: 7000
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: micro-service-1-id
          uri: lb://micro-service-1
          predicates:
            - Path=/microservice1/*
        - id: micro-service-2-id
          uri: lb://micro-service-2
          predicates:
            - Path=/microservice2/*
          filters:
            - AddRequestHeader=first-request, first-request-header
            - AddResponseHeader=first-response, first-response-header


