server:
  port: 7000
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: comptes-id
          uri: lb://comptes
          predicates:
            - Path=/comptes/*
        - id: produits-id
          uri: lb://produits
          predicates:
            - Path=/produits/*
        - id: commandes-id
            uri: lb://commandes
            predicates:
              - Path=/commandes/*
          filters:
            - AddRequestHeader=first-request, first-request-header
            - AddResponseHeader=first-response, first-response-header


