server:
  port: 8084
spring:
  application:
    name: gestion-comptes
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/gestion-comptes
    password:
  jpa:
    hibernate:
      ddl-auto: update